-- 코드를 입력하세요
WITH TRUCK_HISTORY AS (
    SELECT
      ch.HISTORY_ID,
      cc.CAR_TYPE,
      cc.DAILY_FEE,
      DATEDIFF(ch.END_DATE, ch.START_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS ch
    JOIN CAR_RENTAL_COMPANY_CAR AS cc
      ON ch.CAR_ID = cc.CAR_ID
    WHERE cc.CAR_TYPE = '트럭'
)
SELECT 
  th.HISTORY_ID,
  FLOOR(th.DURATION * th.DAILY_FEE * (100 - IFNULL(cd.DISCOUNT_RATE, 0)) / 100) AS FEE 
FROM TRUCK_HISTORY AS th
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS cd
  ON th.CAR_TYPE = cd.CAR_TYPE
  AND (
       (th.DURATION >= 90 AND cd.DURATION_TYPE = '90일 이상') OR
       (th.DURATION >= 30 AND th.DURATION < 90 AND cd.DURATION_TYPE = '30일 이상') OR
       (th.DURATION >= 7 AND th.DURATION < 30 AND cd.DURATION_TYPE = '7일 이상')
   )
ORDER BY FEE DESC, th.HISTORY_ID DESC;