-- 코드를 입력하세요
SELECT
  USER_ID,
  NICKNAME,
  TOTAL_SALES
FROM (SELECT  
        usu.USER_ID AS USER_ID,
        usu.NICKNAME AS NICKNAME,
        SUM(ugb.PRICE) AS TOTAL_SALES
      FROM USED_GOODS_BOARD AS ugb
      LEFT JOIN USED_GOODS_USER AS usu
        ON ugb.WRITER_ID = usu.USER_ID
      WHERE ugb.STATUS = 'DONE'
      GROUP BY usu.USER_ID, usu.NICKNAME
     ) AS SUBQUERY
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;
