-- 코드를 입력하세요
SELECT
 DISTINCT(ch.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS cc
RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS ch
        ON cc.CAR_ID = ch.CAR_ID
WHERE cc.CAR_TYPE = '세단'
  AND MONTH(ch.START_DATE) = 10
GROUP BY ch.CAR_ID
ORDER BY ch.CAR_ID DESC;